[build]
buildCommand = "npx prisma generate && npm run build"

[build.cache]
paths = ["node_modules", ".next/cache"]

[deploy]
startCommand = "npx prisma migrate deploy && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
